### ISSUE TITLE
Computing energy

### ISSUE THREAD

**Issue by ZeWang95** [bpucla/latent-space-EBM-prior#2]
In train_svhn.py L461, why the score is negated for tanh, while not for the orther activations?
Thanks!

**Comment by bpucla** [comment]
That's just one option we used in our early experiments. The reported results are all based the identity activation. See https://github.com/bpucla/latent-space-EBM-prior/blob/a530d0fbfe995cc0dcff14c27170a7cf77492114/train_svhn.py#L58

**Comment by ZeWang95** [comment]
Thanks!
